name: syncfusion_officecore
description: Syncfusion Flutter Office Core is a library written natively in Dart for creating Office documents from scratch.
version: 18.3.35-beta
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.1.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
