name: syncfusion_officechart
description: Syncfusion Flutter Office Chart is a library written natively in Dart for creating Office charts from scratch.
version: 18.3.35-beta
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.1.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  xml: ^4.5.1
  archive: ^2.0.13
  syncfusion_flutter_xlsio: 
    path: ../syncfusion_flutter_xlsio
