name: officecore_example
description: Demo for creating a Excel file using syncfusion_flutter_officecore package.

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.7
  open_file: ^3.0.1
  syncfusion_flutter_xlsio:
     git:
      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-xlsio
      path: flutter_xlsio/syncfusion_flutter_xlsio
      branch: release/18.4.0.1
      ref: release/18.4.0.1


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
