name: pdf_example
description: Demo for creating a PDF file using syncfusion_flutter_pdf package.

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.7
  open_file: ^3.0.1
  syncfusion_flutter_pdf:
    path: ../

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
